package com.orion.templete.presentation.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val ColorPrimaryLight = Color(0xFF3E2318)
val ColorPrimaryVariantLight = Color(0xFF4267B2)
val ColorSecondaryLight = Color(0xFF0E5AFA)
val ColorSecondaryVariantLight = Color(0xFFB8B8B8)
val ColorBackgroundLight = Color(0xFFF2F3F5)
val ColorSurfaceLight = Color(0xFFFFFFFF)
val ColorErrorLight = Color(0xFFF44336)
val ColorOnPrimaryLight = Color(0xFFFFFFFF)
val ColorOnSecondaryLight = Color(0xFFFFFFFF)
val ColorOnBackgroundLight = Color(0xFF000000)
val ColorOnSurfaceLight = Color(0xFF000000)
val ColorOnErrorLight = Color(0xFFFFFFFF)
val ColorIsLightLight = Color(0xFFFFFFFF)

val ColorTextPrimaryLight = Color(0xFF000000)
val ColorTextSecondaryLight = Color(0xFF505050)
val ColorTextTertiaryLight = Color(0xFF676767)
val FloatingActionButtonLight = Color(0xFF0E5AFA)

val ColorInputBorderLight = Color(0xFFEAEAEA)
val ColorInputBgLight = Color(0xFFFFFFFF)
val ColorButtonBgPrimaryLight = Color(0xFF000000)
val ColorButtonTextPrimaryLight = Color(0xFFFFFFFF)
val ColorItemAddToggleBgLight = Color(0xFFFFFFFF)
val ColorItemAddToggleTextLight = Color(0xFF000000)
val ColorItemOnlineStorePhotoBorderLight = Color(0xFF505050)

val ColorPrimaryDark = Color(0xFF3E2318)
val ColorPrimaryVariantDark = Color(0xFF4267B2)
val ColorSecondaryDark = Color(0xFF0E5AFA)
val ColorSecondaryVariantDark = Color(0xFFFFFFFF)
val ColorBackgroundDark = Color(0xFF18191A)
val ColorSurfaceDark = Color(0xFF242526)
val ColorErrorDark = Color(0xFFF44336)
val ColorOnPrimaryDark = Color(0xFFFFFFFF)
val ColorOnSecondaryDark = Color(0xFFBFBFC0)
val ColorOnBackgroundDark = Color(0xFFFFFFFF)
val ColorOnSurfaceDark = Color(0xFFE3E6EA)
val ColorOnErrorDark = Color(0xFFFFFFFF)
val ColorIsLightDark = Color(0xFFFFFFFF)

val ColorTextPrimaryDark = Color(0xFFE3E6EA)
val ColorTextSecondaryDark = Color(0xFFA9ACB1)
val ColorTextTertiaryDark = Color(0xFF919297)

val ColorInputBorderDark = Color(0xFF3A3B3C)
val ColorInputBgDark = Color(0xFF3A3B3C)
val ColorButtonBgPrimaryDark = Color(0xFF1A73E9)
val ColorButtonTextPrimaryDark = Color(0xFFFFFFFF)
val ColorItemAddToggleBgDark = Color(0xFF242526)
val ColorItemAddToggleTextDark = Color(0xFFE3E6EA)
val ColorItemOnlineStorePhotoBorderDark = Color(0xFFE3E6EA)
